export const ADD_TASK = 'ADD_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const SAVE_TASKS = 'SAVE_TASKS';
export const ADD_TASKS_FROM_API = 'ADD_TASKS_FROM_API';
export const SHOW_SERVER_ALERT = 'SHOW_SERVER_ALERT';
export const HIDE_SERVER_ALERT = 'HIDE_SERVER_ALERT';
export const SHOW_ADD_MODAL = 'SHOW_ADD_MODAL';

