export const ADD_TASK = 'ADD_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const SAVE_TASKS = 'SAVE_TASKS';
export const ADD_TASKS_FROM_API = 'ADD_TASKS_FROM_API';
export const SHOW_SAVED_MESSAGE = 'SHOW_SAVED_MESSAGE';
export const HIDE_SAVED_MESSAGE = 'HIDE_SAVED_MESSAGE';
export const SHOW_ADD_MODAL = 'SHOW_ADD_MODAL';

